
parentserver:
  container_name: parentserver
  restart: always
  build: ./parentserver
  expose:
    - "8000"
  links:
    - postgres:postgres
    - authserver:authserver
    - locationserver:locationserver
  volumes:
    - /root/cannablr/cannablr/static
    - /root/cannablr/cannablr/media
  env_file: .env
  command: ./startup.sh

authserver:
  container_name: authserver
  restart: always
  build: ./authserver
  expose:
    - "5000"
  links:
    - redis:redis
  environment:
    DEBUG: 'true'

locationserver:
  container_name: locationserver
  restart: always
  build: ./locationserver
  expose:
    - "8000"
  links:
    - postgres:postgres
    - authserver:authserver
  env_file: .env
  command: ./startup.sh

postgres:
  container_name: postgres
  restart: always
  image: kartoza/postgis:9.4-2.1
  ports:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  container_name: redis 
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

nginx:
  container_name: nginx
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:    
    - parentserver
  links:
    - parentserver:parentserver