authserver:
  container_name: authserver
  restart: always
  build: ./authserver
  expose:
    - "8000"
  links:
    - redis:redis
  environment:
    DEBUG: 'true'

parentserver:
  container_name: parentserver
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - authserver:authserver
  volumes:
    - /usr/src/app
    - /usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: ./startup.sh

postgres:
  restart: always
  image: kartoza/postgis:9.4-2.1
  ports:
    - "5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

