stack: donnaloia/cannablr
services:
  parentserver:
    build: ./parentserver
    links:
      - postgres:postgres
      - authserver:authserver
      - locationserver:locationserver
    volumes:
      - /root/cannablr/cannablr/static
      - /root/cannablr/cannablr/media
    env_file: .env
    command: ./startup.sh

  authserver:
    build: ./authserver
    links:
      - redis:redis
    environment:
      DEBUG: 'true'

  locationserver:
    build: ./locationserver
    links:
      - postgres:postgres
      - authserver:authserver
    env_file: .env
    command: ./startup.sh

  postgres:
    image: kartoza/postgis:9.4-2.1
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:    
      - parentserver
    links:
      - parentserver:parentserver